# Spring Boot Application Configuration
spring.application.name=happimom-backend
server.port=${SERVER_PORT}

# MySQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Multipart Upload Configuration for Images, Videos & PDFs (up to 100MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:ehi0amss}
cloudinary.api-key=${CLOUDINARY_API_KEY:168881922637239}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:xwM3RLp9lp1zij42iRwKv7dRL4A}
cloudinary.upload-preset=${CLOUDINARY_UPLOAD_PRESET:}

