package com.healthcare.happimom.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatResponseDTO {
    /**
     * The response generated by the AI assistant.
     */
    private String reply;

    /**
     * Which AI engine produced the response: "Groq (qwen/qwen3.8-27b)" or "Google Gemini".
     */
    private String modelUsed;

    /**
     * Standard informational disclaimer.
     */
    private String disclaimer;
}
